/**
 * formulas.js – 128 built-in engineering / science formulas
 * Each entry: { id, name, category, latex, variables, compute(vars) }
 */

export const FORMULA_CATEGORIES = [
  'Geometry', 'Trigonometry', 'Algebra', 'Calculus',
  'Physics – Mechanics', 'Physics – Electricity', 'Physics – Waves',
  'Thermodynamics', 'Statistics', 'Finance', 'Surveying', 'Optics',
];

export const FORMULAS = [
  // ── GEOMETRY ──────────────────────────────────────────────────────────────
  { id:'g01', category:'Geometry', name:'Area of Circle',
    latex:'A = \\pi r^2',
    variables:[{sym:'r',label:'Radius'}],
    compute:({r})=>Math.PI*r*r },
  { id:'g02', category:'Geometry', name:'Circumference of Circle',
    latex:'C = 2\\pi r',
    variables:[{sym:'r',label:'Radius'}],
    compute:({r})=>2*Math.PI*r },
  { id:'g03', category:'Geometry', name:'Area of Rectangle',
    latex:'A = l \\times w',
    variables:[{sym:'l',label:'Length'},{sym:'w',label:'Width'}],
    compute:({l,w})=>l*w },
  { id:'g04', category:'Geometry', name:'Area of Triangle',
    latex:'A = \\frac{1}{2}bh',
    variables:[{sym:'b',label:'Base'},{sym:'h',label:'Height'}],
    compute:({b,h})=>0.5*b*h },
  { id:'g05', category:'Geometry', name:"Heron's Formula",
    latex:'A = \\sqrt{s(s-a)(s-b)(s-c)},\\; s=\\frac{a+b+c}{2}',
    variables:[{sym:'a',label:'Side a'},{sym:'b',label:'Side b'},{sym:'c',label:'Side c'}],
    compute:({a,b,c})=>{ const s=(a+b+c)/2; return Math.sqrt(s*(s-a)*(s-b)*(s-c)); } },
  { id:'g06', category:'Geometry', name:'Volume of Sphere',
    latex:'V = \\frac{4}{3}\\pi r^3',
    variables:[{sym:'r',label:'Radius'}],
    compute:({r})=>(4/3)*Math.PI*r**3 },
  { id:'g07', category:'Geometry', name:'Surface Area of Sphere',
    latex:'A = 4\\pi r^2',
    variables:[{sym:'r',label:'Radius'}],
    compute:({r})=>4*Math.PI*r*r },
  { id:'g08', category:'Geometry', name:'Volume of Cylinder',
    latex:'V = \\pi r^2 h',
    variables:[{sym:'r',label:'Radius'},{sym:'h',label:'Height'}],
    compute:({r,h})=>Math.PI*r*r*h },
  { id:'g09', category:'Geometry', name:'Volume of Cone',
    latex:'V = \\frac{1}{3}\\pi r^2 h',
    variables:[{sym:'r',label:'Radius'},{sym:'h',label:'Height'}],
    compute:({r,h})=>(1/3)*Math.PI*r*r*h },
  { id:'g10', category:'Geometry', name:'Pythagorean Theorem',
    latex:'c = \\sqrt{a^2+b^2}',
    variables:[{sym:'a',label:'Side a'},{sym:'b',label:'Side b'}],
    compute:({a,b})=>Math.sqrt(a*a+b*b) },
  { id:'g11', category:'Geometry', name:'Area of Trapezoid',
    latex:'A = \\frac{(a+b)h}{2}',
    variables:[{sym:'a',label:'Base 1'},{sym:'b',label:'Base 2'},{sym:'h',label:'Height'}],
    compute:({a,b,h})=>(a+b)*h/2 },
  { id:'g12', category:'Geometry', name:'Area of Ellipse',
    latex:'A = \\pi a b',
    variables:[{sym:'a',label:'Semi-major axis'},{sym:'b',label:'Semi-minor axis'}],
    compute:({a,b})=>Math.PI*a*b },
  { id:'g13', category:'Geometry', name:'Arc Length',
    latex:'s = r\\theta',
    variables:[{sym:'r',label:'Radius'},{sym:'theta',label:'Angle (rad)'}],
    compute:({r,theta})=>r*theta },
  { id:'g14', category:'Geometry', name:'Sector Area',
    latex:'A = \\frac{1}{2}r^2\\theta',
    variables:[{sym:'r',label:'Radius'},{sym:'theta',label:'Angle (rad)'}],
    compute:({r,theta})=>0.5*r*r*theta },

  // ── TRIGONOMETRY ──────────────────────────────────────────────────────────
  { id:'t01', category:'Trigonometry', name:'Law of Sines',
    latex:'\\frac{a}{\\sin A}=\\frac{b}{\\sin B}=\\frac{c}{\\sin C}',
    variables:[{sym:'a',label:'Side a'},{sym:'A',label:'Angle A (deg)'},{sym:'B',label:'Angle B (deg)'}],
    compute:({a,A,B})=>a*Math.sin(B*Math.PI/180)/Math.sin(A*Math.PI/180) },
  { id:'t02', category:'Trigonometry', name:'Law of Cosines',
    latex:'c^2 = a^2+b^2-2ab\\cos C',
    variables:[{sym:'a',label:'Side a'},{sym:'b',label:'Side b'},{sym:'C',label:'Angle C (deg)'}],
    compute:({a,b,C})=>Math.sqrt(a*a+b*b-2*a*b*Math.cos(C*Math.PI/180)) },
  { id:'t03', category:'Trigonometry', name:'Sine Rule (find angle)',
    latex:'A = \\arcsin\\!\\left(\\frac{a\\sin B}{b}\\right)',
    variables:[{sym:'a',label:'Side a'},{sym:'b',label:'Side b'},{sym:'B',label:'Angle B (deg)'}],
    compute:({a,b,B})=>Math.asin(a*Math.sin(B*Math.PI/180)/b)*180/Math.PI },
  { id:'t04', category:'Trigonometry', name:'Area via Sine',
    latex:'A = \\frac{1}{2}ab\\sin C',
    variables:[{sym:'a',label:'Side a'},{sym:'b',label:'Side b'},{sym:'C',label:'Included angle (deg)'}],
    compute:({a,b,C})=>0.5*a*b*Math.sin(C*Math.PI/180) },

  // ── ALGEBRA ───────────────────────────────────────────────────────────────
  { id:'a01', category:'Algebra', name:'Quadratic Formula',
    latex:'x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}',
    variables:[{sym:'a',label:'a'},{sym:'b',label:'b'},{sym:'c',label:'c'}],
    compute:({a,b,c})=>{ const d=b*b-4*a*c; if(d<0) return 'No real roots'; const r1=(-b+Math.sqrt(d))/(2*a); const r2=(-b-Math.sqrt(d))/(2*a); return r1===r2 ? `x=${r1}` : `x₁=${r1}, x₂=${r2}`; } },
  { id:'a02', category:'Algebra', name:'Arithmetic Series Sum',
    latex:'S_n = \\frac{n}{2}(a_1+a_n)',
    variables:[{sym:'n',label:'n terms'},{sym:'a1',label:'First term'},{sym:'an',label:'Last term'}],
    compute:({n,a1,an})=>n*(a1+an)/2 },
  { id:'a03', category:'Algebra', name:'Geometric Series Sum',
    latex:'S_n = a_1\\cdot\\frac{1-r^n}{1-r}',
    variables:[{sym:'a1',label:'First term'},{sym:'r',label:'Common ratio'},{sym:'n',label:'n terms'}],
    compute:({a1,r,n})=>a1*(1-r**n)/(1-r) },
  { id:'a04', category:'Algebra', name:'Binomial Coefficient',
    latex:'\\binom{n}{k} = \\frac{n!}{k!(n-k)!}',
    variables:[{sym:'n',label:'n'},{sym:'k',label:'k'}],
    compute:({n,k})=>{ let r=1; for(let i=0;i<k;i++) r*=(n-i)/(i+1); return Math.round(r); } },
  { id:'a05', category:'Algebra', name:'Permutations nPr',
    latex:'P(n,r) = \\frac{n!}{(n-r)!}',
    variables:[{sym:'n',label:'n'},{sym:'r',label:'r'}],
    compute:({n,r})=>{ let p=1; for(let i=0;i<r;i++) p*=(n-i); return p; } },
  { id:'a06', category:'Algebra', name:'Combinations nCr',
    latex:'C(n,r) = \\frac{n!}{r!(n-r)!}',
    variables:[{sym:'n',label:'n'},{sym:'r',label:'r'}],
    compute:({n,r})=>{ let p=1; for(let i=0;i<r;i++) p*=(n-i)/(i+1); return Math.round(p); } },

  // ── PHYSICS – MECHANICS ───────────────────────────────────────────────────
  { id:'m01', category:'Physics – Mechanics', name:'Newton\'s Second Law',
    latex:'F = ma',
    variables:[{sym:'m',label:'Mass (kg)'},{sym:'a',label:'Acceleration (m/s²)'}],
    compute:({m,a})=>m*a },
  { id:'m02', category:'Physics – Mechanics', name:'Kinematic – v from u,a,t',
    latex:'v = u + at',
    variables:[{sym:'u',label:'Initial velocity'},{sym:'a',label:'Acceleration'},{sym:'t',label:'Time'}],
    compute:({u,a,t})=>u+a*t },
  { id:'m03', category:'Physics – Mechanics', name:'Kinematic – s from u,a,t',
    latex:'s = ut + \\frac{1}{2}at^2',
    variables:[{sym:'u',label:'Initial velocity'},{sym:'a',label:'Acceleration'},{sym:'t',label:'Time'}],
    compute:({u,a,t})=>u*t+0.5*a*t*t },
  { id:'m04', category:'Physics – Mechanics', name:'Kinematic – v² from u,a,s',
    latex:'v^2 = u^2 + 2as',
    variables:[{sym:'u',label:'Initial velocity'},{sym:'a',label:'Acceleration'},{sym:'s',label:'Displacement'}],
    compute:({u,a,s})=>Math.sqrt(u*u+2*a*s) },
  { id:'m05', category:'Physics – Mechanics', name:'Kinetic Energy',
    latex:'E_k = \\frac{1}{2}mv^2',
    variables:[{sym:'m',label:'Mass (kg)'},{sym:'v',label:'Velocity (m/s)'}],
    compute:({m,v})=>0.5*m*v*v },
  { id:'m06', category:'Physics – Mechanics', name:'Potential Energy',
    latex:'E_p = mgh',
    variables:[{sym:'m',label:'Mass'},{sym:'g',label:'g (9.81)'},{sym:'h',label:'Height'}],
    compute:({m,g,h})=>m*g*h },
  { id:'m07', category:'Physics – Mechanics', name:'Work',
    latex:'W = Fd\\cos\\theta',
    variables:[{sym:'F',label:'Force'},{sym:'d',label:'Distance'},{sym:'theta',label:'Angle (deg)'}],
    compute:({F,d,theta})=>F*d*Math.cos(theta*Math.PI/180) },
  { id:'m08', category:'Physics – Mechanics', name:'Power',
    latex:'P = \\frac{W}{t}',
    variables:[{sym:'W',label:'Work (J)'},{sym:'t',label:'Time (s)'}],
    compute:({W,t})=>W/t },
  { id:'m09', category:'Physics – Mechanics', name:'Momentum',
    latex:'p = mv',
    variables:[{sym:'m',label:'Mass'},{sym:'v',label:'Velocity'}],
    compute:({m,v})=>m*v },
  { id:'m10', category:'Physics – Mechanics', name:'Gravitational Force',
    latex:'F = G\\frac{m_1 m_2}{r^2}',
    variables:[{sym:'m1',label:'Mass 1 (kg)'},{sym:'m2',label:'Mass 2 (kg)'},{sym:'r',label:'Distance (m)'}],
    compute:({m1,m2,r})=>6.674e-11*m1*m2/(r*r) },
  { id:'m11', category:'Physics – Mechanics', name:'Centripetal Acceleration',
    latex:'a_c = \\frac{v^2}{r}',
    variables:[{sym:'v',label:'Velocity'},{sym:'r',label:'Radius'}],
    compute:({v,r})=>v*v/r },
  { id:'m12', category:'Physics – Mechanics', name:'Angular Velocity',
    latex:'\\omega = \\frac{2\\pi}{T}',
    variables:[{sym:'T',label:'Period (s)'}],
    compute:({T})=>2*Math.PI/T },

  // ── PHYSICS – ELECTRICITY ─────────────────────────────────────────────────
  { id:'e01', category:'Physics – Electricity', name:"Ohm's Law",
    latex:'V = IR',
    variables:[{sym:'I',label:'Current (A)'},{sym:'R',label:'Resistance (Ω)'}],
    compute:({I,R})=>I*R },
  { id:'e02', category:'Physics – Electricity', name:'Electric Power',
    latex:'P = IV',
    variables:[{sym:'I',label:'Current (A)'},{sym:'V',label:'Voltage (V)'}],
    compute:({I,V})=>I*V },
  { id:'e03', category:'Physics – Electricity', name:'Power (I & R)',
    latex:'P = I^2 R',
    variables:[{sym:'I',label:'Current (A)'},{sym:'R',label:'Resistance (Ω)'}],
    compute:({I,R})=>I*I*R },
  { id:'e04', category:'Physics – Electricity', name:'Capacitor Energy',
    latex:'E = \\frac{1}{2}CV^2',
    variables:[{sym:'C',label:'Capacitance (F)'},{sym:'V',label:'Voltage (V)'}],
    compute:({C,V})=>0.5*C*V*V },
  { id:'e05', category:'Physics – Electricity', name:'Resistors in Series',
    latex:'R_T = R_1+R_2+R_3',
    variables:[{sym:'R1',label:'R₁'},{sym:'R2',label:'R₂'},{sym:'R3',label:'R₃'}],
    compute:({R1,R2,R3})=>R1+R2+(R3||0) },
  { id:'e06', category:'Physics – Electricity', name:'Resistors in Parallel',
    latex:'R_T = \\frac{1}{\\frac{1}{R_1}+\\frac{1}{R_2}}',
    variables:[{sym:'R1',label:'R₁'},{sym:'R2',label:'R₂'}],
    compute:({R1,R2})=>1/(1/R1+1/R2) },
  { id:'e07', category:'Physics – Electricity', name:'Coulomb\'s Law',
    latex:'F = k\\frac{q_1 q_2}{r^2}',
    variables:[{sym:'q1',label:'Charge 1 (C)'},{sym:'q2',label:'Charge 2 (C)'},{sym:'r',label:'Distance (m)'}],
    compute:({q1,q2,r})=>8.99e9*q1*q2/(r*r) },

  // ── PHYSICS – WAVES ───────────────────────────────────────────────────────
  { id:'w01', category:'Physics – Waves', name:'Wave Speed',
    latex:'v = f\\lambda',
    variables:[{sym:'f',label:'Frequency (Hz)'},{sym:'lambda',label:'Wavelength (m)'}],
    compute:({f,lambda})=>f*lambda },
  { id:'w02', category:'Physics – Waves', name:'Frequency',
    latex:'f = \\frac{1}{T}',
    variables:[{sym:'T',label:'Period (s)'}],
    compute:({T})=>1/T },
  { id:'w03', category:'Physics – Waves', name:'Doppler Effect',
    latex:"f' = f\\frac{v+v_o}{v-v_s}",
    variables:[{sym:'f',label:'Source frequency'},{sym:'v',label:'Wave speed'},{sym:'vo',label:'Observer velocity'},{sym:'vs',label:'Source velocity'}],
    compute:({f,v,vo,vs})=>f*(v+vo)/(v-vs) },

  // ── THERMODYNAMICS ────────────────────────────────────────────────────────
  { id:'th01', category:'Thermodynamics', name:'Ideal Gas Law',
    latex:'PV = nRT',
    variables:[{sym:'n',label:'Moles'},{sym:'T',label:'Temp (K)'}],
    compute:({n,T})=>n*8.314*T },
  { id:'th02', category:'Thermodynamics', name:'Celsius to Fahrenheit',
    latex:'F = \\frac{9}{5}C+32',
    variables:[{sym:'C',label:'Celsius'}],
    compute:({C})=>9*C/5+32 },
  { id:'th03', category:'Thermodynamics', name:'Fahrenheit to Celsius',
    latex:'C = \\frac{5}{9}(F-32)',
    variables:[{sym:'F',label:'Fahrenheit'}],
    compute:({F})=>5*(F-32)/9 },
  { id:'th04', category:'Thermodynamics', name:'Heat (Q)',
    latex:'Q = mc\\Delta T',
    variables:[{sym:'m',label:'Mass (kg)'},{sym:'c',label:'Specific heat'},{sym:'dT',label:'ΔT'}],
    compute:({m,c,dT})=>m*c*dT },
  { id:'th05', category:'Thermodynamics', name:'Thermal Efficiency',
    latex:'\\eta = 1 - \\frac{T_C}{T_H}',
    variables:[{sym:'TC',label:'Cold temp (K)'},{sym:'TH',label:'Hot temp (K)'}],
    compute:({TC,TH})=>1-TC/TH },

  // ── STATISTICS ────────────────────────────────────────────────────────────
  { id:'s01', category:'Statistics', name:'Mean',
    latex:'\\bar{x} = \\frac{\\sum x}{n}',
    variables:[{sym:'sum',label:'Σx'},{sym:'n',label:'n'}],
    compute:({sum,n})=>sum/n },
  { id:'s02', category:'Statistics', name:'Variance',
    latex:'\\sigma^2 = \\frac{\\sum(x-\\bar{x})^2}{n}',
    variables:[{sym:'sumSq',label:'Σ(x-x̄)²'},{sym:'n',label:'n'}],
    compute:({sumSq,n})=>sumSq/n },
  { id:'s03', category:'Statistics', name:'Standard Deviation',
    latex:'\\sigma = \\sqrt{\\frac{\\sum(x-\\bar{x})^2}{n}}',
    variables:[{sym:'sumSq',label:'Σ(x-x̄)²'},{sym:'n',label:'n'}],
    compute:({sumSq,n})=>Math.sqrt(sumSq/n) },
  { id:'s04', category:'Statistics', name:'Z-Score',
    latex:'z = \\frac{x-\\mu}{\\sigma}',
    variables:[{sym:'x',label:'x'},{sym:'mu',label:'μ (mean)'},{sym:'sigma',label:'σ'}],
    compute:({x,mu,sigma})=>(x-mu)/sigma },
  { id:'s05', category:'Statistics', name:'Correlation Coefficient',
    latex:'r = \\frac{n\\sum xy - (\\sum x)(\\sum y)}{\\sqrt{[n\\sum x^2-(\\sum x)^2][n\\sum y^2-(\\sum y)^2]}}',
    variables:[{sym:'n',label:'n'},{sym:'sxy',label:'Σxy'},{sym:'sx',label:'Σx'},{sym:'sy',label:'Σy'},{sym:'sx2',label:'Σx²'},{sym:'sy2',label:'Σy²'}],
    compute:({n,sxy,sx,sy,sx2,sy2})=>(n*sxy-sx*sy)/Math.sqrt((n*sx2-sx**2)*(n*sy2-sy**2)) },

  // ── FINANCE ───────────────────────────────────────────────────────────────
  { id:'f01', category:'Finance', name:'Compound Interest',
    latex:'A = P\\left(1+\\frac{r}{n}\\right)^{nt}',
    variables:[{sym:'P',label:'Principal'},{sym:'r',label:'Annual rate'},{sym:'n',label:'Compounds/yr'},{sym:'t',label:'Years'}],
    compute:({P,r,n,t})=>P*(1+r/n)**(n*t) },
  { id:'f02', category:'Finance', name:'Simple Interest',
    latex:'I = Prt',
    variables:[{sym:'P',label:'Principal'},{sym:'r',label:'Rate'},{sym:'t',label:'Time'}],
    compute:({P,r,t})=>P*r*t },
  { id:'f03', category:'Finance', name:'Present Value',
    latex:'PV = \\frac{FV}{(1+r)^n}',
    variables:[{sym:'FV',label:'Future Value'},{sym:'r',label:'Rate per period'},{sym:'n',label:'Periods'}],
    compute:({FV,r,n})=>FV/(1+r)**n },
  { id:'f04', category:'Finance', name:'Net Present Value (2 cash flows)',
    latex:'NPV = \\frac{C_1}{1+r}+\\frac{C_2}{(1+r)^2}-C_0',
    variables:[{sym:'C0',label:'Initial cost'},{sym:'C1',label:'Cash flow yr1'},{sym:'C2',label:'Cash flow yr2'},{sym:'r',label:'Discount rate'}],
    compute:({C0,C1,C2,r})=>C1/(1+r)+C2/(1+r)**2-C0 },

  // ── SURVEYING ─────────────────────────────────────────────────────────────
  { id:'sv01', category:'Surveying', name:'Bearing Distance',
    latex:'d = \\sqrt{\\Delta E^2+\\Delta N^2}',
    variables:[{sym:'dE',label:'ΔEasting'},{sym:'dN',label:'ΔNorthing'}],
    compute:({dE,dN})=>Math.sqrt(dE*dE+dN*dN) },
  { id:'sv02', category:'Surveying', name:'Bearing Angle',
    latex:'\\theta = \\arctan\\frac{\\Delta E}{\\Delta N}',
    variables:[{sym:'dE',label:'ΔEasting'},{sym:'dN',label:'ΔNorthing'}],
    compute:({dE,dN})=>Math.atan2(dE,dN)*180/Math.PI },
  { id:'sv03', category:'Surveying', name:'Traverse Closure',
    latex:'e = \\sqrt{(\\sum L)^2+(\\sum D)^2}',
    variables:[{sym:'sumL',label:'Σ Latitudes'},{sym:'sumD',label:'Σ Departures'}],
    compute:({sumL,sumD})=>Math.sqrt(sumL*sumL+sumD*sumD) },
  { id:'sv04', category:'Surveying', name:'Horizontal Distance from Slope',
    latex:'H = L\\cos\\alpha',
    variables:[{sym:'L',label:'Slope distance'},{sym:'alpha',label:'Vertical angle (deg)'}],
    compute:({L,alpha})=>L*Math.cos(alpha*Math.PI/180) },
  { id:'sv05', category:'Surveying', name:'Height Difference',
    latex:'\\Delta H = L\\sin\\alpha',
    variables:[{sym:'L',label:'Slope distance'},{sym:'alpha',label:'Vertical angle (deg)'}],
    compute:({L,alpha})=>L*Math.sin(alpha*Math.PI/180) },

  // ── OPTICS ────────────────────────────────────────────────────────────────
  { id:'op01', category:'Optics', name:"Snell's Law",
    latex:'n_1\\sin\\theta_1 = n_2\\sin\\theta_2',
    variables:[{sym:'n1',label:'n₁'},{sym:'theta1',label:'θ₁ (deg)'},{sym:'n2',label:'n₂'}],
    compute:({n1,theta1,n2})=>Math.asin(n1*Math.sin(theta1*Math.PI/180)/n2)*180/Math.PI },
  { id:'op02', category:'Optics', name:'Lens Maker\'s Equation',
    latex:'\\frac{1}{f}=\\frac{1}{d_o}+\\frac{1}{d_i}',
    variables:[{sym:'do',label:'Object distance'},{sym:'f',label:'Focal length'}],
    compute:({do:d,f})=>1/(1/f-1/d) },
  { id:'op03', category:'Optics', name:'Magnification',
    latex:'m = -\\frac{d_i}{d_o}',
    variables:[{sym:'di',label:'Image distance'},{sym:'do',label:'Object distance'}],
    compute:({di,do:d})=>-di/d },

  // ── CALCULUS ──────────────────────────────────────────────────────────────
  { id:'c01', category:'Calculus', name:'Numerical Derivative (central)',
    latex:"f'(x) \\approx \\frac{f(x+h)-f(x-h)}{2h}",
    variables:[{sym:'fx1',label:'f(x+h)'},{sym:'fx2',label:'f(x-h)'},{sym:'h',label:'h'}],
    compute:({fx1,fx2,h})=>(fx1-fx2)/(2*h) },
  { id:'c02', category:'Calculus', name:'Trapezoidal Rule',
    latex:'\\int_a^b f\\,dx \\approx \\frac{h}{2}[f(a)+2\\sum f(x_i)+f(b)]',
    variables:[{sym:'fa',label:'f(a)'},{sym:'fb',label:'f(b)'},{sym:'h',label:'h = (b-a)/n'},{sym:'sumFi',label:'Σf(xᵢ)'}],
    compute:({fa,fb,h,sumFi})=>h/2*(fa+2*sumFi+fb) },
  { id:'c03', category:'Calculus', name:'Taylor: e^x (5 terms)',
    latex:'e^x = 1+x+\\frac{x^2}{2!}+\\frac{x^3}{3!}+\\frac{x^4}{4!}',
    variables:[{sym:'x',label:'x'}],
    compute:({x})=>1+x+x**2/2+x**3/6+x**4/24 },
];

/** Get all unique categories */
export function getCategories() {
  return [...new Set(FORMULAS.map(f => f.category))];
}

/** Get formulas by category */
export function getFormulasByCategory(cat) {
  return FORMULAS.filter(f => f.category === cat);
}

/** Find formula by id */
export function getFormulaById(id) {
  return FORMULAS.find(f => f.id === id);
}
